update clients for separate utterances
nvidia-riva/cpp-clients pull request #44
Opened 2023-02-16 18:10 UTC by virajkarandikar

2023-03-16 19:33 UTC, messiaen requested changes

2023-03-16 19:33 UTC, messiaen commented on riva/clients/asr/riva_asr_client_helper.cc
> +AppendResult(
This will just combine the separated utterances into one transcript.  Doesn't that defeat the purpose?

2023-03-23 19:23 UTC, virajkarandikar commented on riva/clients/asr/riva_asr_client_helper.cc
> +AppendResult(
All the tests expect the combined transcript.
Also this is an example client. Customer can choose to modify it as needed.

2023-03-23 20:00 UTC, junkin approved these changes
lgtm

2023-04-06 11:48 UTC, virajkarandikar commented
@messiaen can you review?

2023-04-06 14:56 UTC, messiaen approved these changes
LGTM.  Looks like CI may need to be rerun.

2023-04-06 19:41 UTC, merged